### ISSUE TITLE
运势服务器挂了

### ISSUE THREAD

**Issue by GreenChennai** [Yiwen-Chan/fortune#4]
运势服务器挂了
很久了都发不出
能不能修复一下

**Comment by kanrichan** [comment]
一直没有挂。。。

**Comment by GreenChennai** [comment]
![Screenshot_20210626145107](https://user-images.githubusercontent.com/33357929/123504881-86dfa280-d621-11eb-8d94-50990e00f104.jpg)
的确是没有了

**Comment by kanrichan** [comment]
你用的哪个端呢，还有版本号呢

**Comment by GreenChennai** [comment]
mirai的玲心插件
fortune-EPK-v1.0.4.epk

**Comment by kanrichan** [comment]
可后台看其他的这个版本的请求正常啊

**Comment by GreenChennai** [comment]
那或许是我vps提供商网络问题，我再下载一个安装试试

**Comment by GreenChennai** [comment]
那或许是我vps提供商网络问题，我再下载一个安装试试

**Comment by GreenChennai** [comment]
那或许是我vps提供商网络问题了
我重新安装也还是一样
